// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260214212639_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc69f73c-acde-4f3c-b9aa-4f9cf4aaad64"),
                            CreatedAt = new DateTime(2026, 2, 14, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7298),
                            Description = "Initial Project API",
                            Name = "Project Manager v1",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("829698f6-d9c4-454e-8baf-8f5dab9a788d"),
                            CreatedAt = new DateTime(2026, 2, 14, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7462),
                            Description = "Install packages and run migrations",
                            DueDate = new DateTime(2026, 2, 21, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7456),
                            Priority = 2,
                            ProjectId = new Guid("fc69f73c-acde-4f3c-b9aa-4f9cf4aaad64"),
                            Status = 2,
                            Title = "Configure database"
                        },
                        new
                        {
                            Id = new Guid("26edf2f3-0cda-4e9c-97e1-e55ae1da4f3f"),
                            CreatedAt = new DateTime(2026, 2, 14, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7468),
                            Description = "Implementation of Repository Pattern for the Project",
                            DueDate = new DateTime(2026, 2, 24, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7467),
                            Priority = 1,
                            ProjectId = new Guid("fc69f73c-acde-4f3c-b9aa-4f9cf4aaad64"),
                            Status = 1,
                            Title = "Generate Repo"
                        },
                        new
                        {
                            Id = new Guid("18015c01-ba84-41fb-8536-4ad5246f20b8"),
                            CreatedAt = new DateTime(2026, 2, 14, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7472),
                            Description = "Generate README of the Project",
                            DueDate = new DateTime(2026, 3, 1, 21, 26, 38, 546, DateTimeKind.Utc).AddTicks(7471),
                            Priority = 0,
                            ProjectId = new Guid("fc69f73c-acde-4f3c-b9aa-4f9cf4aaad64"),
                            Status = 0,
                            Title = "Tech documentation"
                        });
                });

            modelBuilder.Entity("Models.TaskItem", b =>
                {
                    b.HasOne("Models.Project", "Project")
                        .WithMany("TaskItems")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Models.Project", b =>
                {
                    b.Navigation("TaskItems");
                });
#pragma warning restore 612, 618
        }
    }
}
